### ISSUE TITLE
How to run on Expo?

### ISSUE THREAD

**Issue by SeanRenet** [blazerroad/react-native-image-video-picker-editor#1]
I installed this on expo and got an error on ios that says `Invariant Violation:  Native module cannot be null.
`
The error on android is `CameraManager.checkIfRecordAudioPerssionsAreDefied is not a function`

Is there some way to install this on react-native expo?

**Comment by blazerroad** [comment]
No you should inject from EXPO

**Comment by shayegh** [comment]
Hi,
is there any plan to enable using this amazing component in expo
